const name = "risano"
const email = "risano@gmail.com"
const fullName = "risano akbar"
const descriptionLogin = "user login menggunakan email dan passwrod"
const descriptionRegister = "ketika register user menimputkan first name, last name, email, password "
